services:
  app:
    image: adipatidhany/aksara:latest
    # build: .
    ports:
      - "${PORT:-8080}:8080"
    env_file: .env
    environment:
      PORT: "8080"
      DATA_DIR: /data
      STORAGE_DIR: /storage
      PYTHON_BIN: python3
      PARSER_SCRIPT: /app/parser/extract.py
    volumes:
      - ai-reader-data:/data
      - ai-reader-storage:/storage
    dns:
      - 8.8.8.8
      - 1.1.1.1
    restart: unless-stopped

volumes:
  ai-reader-data:
  ai-reader-storage:
